apiVersion: v1
kind: Service
metadata:
  name: "svc-{{include "gitlab.name" .}}"
  namespace: "{{.Release.Namespace}}"
spec:
  ports:
    - name: gitlab-web
      protocol: TCP
      port: 80
    - name: gitlab-ssh
      protocol: TCP
      port: 22
  selector:
    app: "{{- .Release.Name -}}"
    version: "{{- .Chart.Version -}}"
    ns: "{{- .Release.Namespace -}}"
---
{{- if .Values.external_ssh.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: "svc-{{include "gitlab.name" .}}-ssh"
  namespace: "{{.Release.Namespace}}"
  annotations:
    {{- range  $key, $val := .Values.external_ssh.annotations}}
    {{$key}}: "{{$val}}"
    {{- end}}
spec:
  ports:
    - name: gitlab-ssh
      protocol: TCP
      port: 22
  selector:
    app: "{{- .Release.Name -}}"
    version: "{{- .Chart.Version -}}"
    ns: "{{- .Release.Namespace -}}"
  type: LoadBalancer
  {{- if .Values.external_ssh.loadBalancerIP}}
  loadBalancerIP: {{.Values.external_ssh.loadBalancerIP}}
  {{- end}}
  {{- end}}
