apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-{{ .Release.Name }}
  namespace: {{.Release.Namespace }}
spec:
  serviceName: "svc-{{ .Release.Name }}"
  selector:
    matchLabels:
      app: "{{- .Release.Name -}}"
      version: "{{- .Chart.Version -}}"
      ns: "{{- .Release.Namespace -}}"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{- .Release.Name -}}"
        version: "{{- .Chart.Version -}}"
        ns: "{{- .Release.Namespace -}}"
    spec:
      containers:
        - name: gitlab-postgres
          image: "{{.Values.image.repository}}/{{.Values.image.images.postgres}}"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d/
          env:
            - name: 'PGDATA'
              value: "/var/lib/postgresql/data/pgdata"
          envFrom:
            - configMapRef:
                name: "conf-{{.Release.Name}}"
            - secretRef:
                name: "secret-{{.Release.Name}}"
          imagePullPolicy: "{{.Values.image.pullPolicy}}"
        - name: gitlab-redis
          image: "{{.Values.image.repository}}/{{.Values.image.images.redis}}"
          imagePullPolicy: "{{.Values.image.pullPolicy}}"
          envFrom:
            - configMapRef:
                name: "conf-{{.Release.Name}}"
            - secretRef:
                name: "secret-{{.Release.Name}}"
          volumeMounts:
            - name: gitlab-redis
              mountPath: /data
        - name: gitlab-server
          image: "{{.Values.image.repository}}/{{.Values.image.images.gitlab}}:{{.Chart.AppVersion}}"
          imagePullPolicy: "{{.Values.image.pullPolicy}}"
          volumeMounts:
            - name: gitlab-data
              mountPath: /home/git/data
          envFrom:
            - configMapRef:
                name: "conf-{{.Release.Name}}"
            - secretRef:
                name: "secret-{{.Release.Name}}"
      volumes:
        {{- with .Values.persistence}}
        - name: gitlab-data
        {{- if .enabled}}
          persistentVolumeClaim:
            claimName: "pvc-{{ include "gitlab.name" $}}-data"
        {{- else}}
          emptyDir: { }
        {{- end }}
        - name: gitlab-redis
        {{- if .enabled}}
          persistentVolumeClaim:
            claimName: "pvc-{{ include "gitlab.name" $}}-redis"
        {{- else}}
          emptyDir: { }
        {{- end }}
        - name: postgres-data
        {{- if .enabled}}
          persistentVolumeClaim:
            claimName: "pvc-{{ include "gitlab.name" $}}-postgres"
        {{- else}}
          emptyDir: { }
        {{- end }}
        - name: postgres-init
          configMap:
            name: "res-{{$.Release.Name}}-pg-init"
        {{- end}}
