apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-{{.Release.Name}}
  namespace: {{.Release.Namespace}}
data:
  GITLAB_HOST: "{{.Values.gitlab.host}}"
  GITLAB_SSH_PORT: "22"
  GITLAB_PORT: "443"
  GITLAB_HTTPS: "true"
  SSL_SELF_SIGNED: "true"
  ############# LDAP Config
  {{- if .Values.gitlab.ldap.enabled }}
  {{- with .Values.gitlab.ldap}}
  LDAP_ENABLED: "true"
  LDAP_LABEL: "{{.label}}"
  LDAP_HOST: "{{.host}}"
  LDAP_PORT: "{{.port}}"
  LDAP_UID: "{{.uidColum}}"
  LDAP_ACTIVE_DIRECTORY: "false"
  LDAP_METHOD: "plain"
  LDAP_BIND_DN: "{{.bindDN}}"
  LDAP_BASE: "{{.usersDN}}"
  LDAP_USERS_FILTER: '{{.usersFilter}}' # <4>
  {{- end }}
  {{- end }}
  ############ DB/Redis Config
  {{- with .Values.database}}
  DB_HOST: "127.0.0.1"
  DB_PORT: "5432"
  DB_NAME: "{{.database}}"
  POSTGRES_DB: "{{.database}}"
  POSTGRES_USER: "{{.username}}"
  DB_USER: "{{.username}}"
  REDIS_HOST: "127.0.0.1"
  REDIS_PORT: "6379"
  {{- end }}
  ###########  Package/Repo/Pages Config
  {{- if .Values.gitlab.pages.enabled }}
  GITLAB_PAGES_ENABLED: "true"
  GITLAB_PAGES_HTTPS: "false"
  GITLAB_PAGES_HTTP: "true"
  GITLAB_PAGES_PORT: "80"
  GITLAB_PAGES_DOMAIN: "{{.Values.gitlab.pages.host}}"
  {{- else}}
  GITLAB_PAGES_ENABLED: "false"
  {{- end }}
  GITLAB_REGISTRY_ENABLED: "false"
  GITLAB_PACKAGES_ENABLED: "false"
