apiVersion: v1
kind: Secret
metadata:
  name: secret-{{.Release.Name}}
  namespace: {{.Release.Namespace}}
stringData:
  {{ with .Values.database }}
  DB_PASS: "{{.password}}"
  POSTGRES_PASSWORD: "{{.password}}"
  {{ end }}
  ADMIN_PASS: '{{var.gitlab.root.password}}' # <6>
  DB_KEY_SECRETS: '{{var.gitlab.db-secrets}}'  # <7>
  SESSION_KEY_SECRETS: '{{var.gitlab.session-secrets}}'  # <7>
  OTP_KEY_SECRETS: '{{var.gitlab.otp-secrets}}' # <7>
  PAGES_KEY_SECRETS: '{{var.gitlab.pages-secrets}}' # <7>
