apiVersion: v1
kind: Secret
metadata:
  name: secret-{{.Release.Name}}
  namespace: {{.Release.Namespace}}
stringData:
  {{- with .Values.database }}
  DB_PASS: "{{.password}}"
  POSTGRES_PASSWORD: "{{.password}}"
  {{- end }}
  {{- with .Values.gitlab.secrets}}
  GITLAB_ROOT_PASSWORD: "{{.defaultPassword}}"
  GITLAB_SECRETS_DB_KEY_BASE: "{{.dbSecrets}}"
  GITLAB_SECRETS_SECRET_KEY_BASE: "{{.sessionSecrets}}"
  GITLAB_SECRETS_OTP_KEY_BASE: "{{.otpSecrets}}"
  GITLAB_PAGES_ACCESS_SECRET: "{{.pagesSecrets}}"
  {{- end }}
  ################# LDAP
  {{- if .Values.gitlab.ldap.enabled}}
  LDAP_PASS: "{{.Values.gitlab.ldap.bindDNPassword}}"
  {{- end }}
