apiVersion: v1
kind: ConfigMap
metadata:
  name: res-{{include "nexus3.name" $ }}-init
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "nexus3.labels" . | nindent 4 }}
data:
  init.sh: |
    #!/bin/bash
    set -e
    PASSWD_PATH=/nexus/admin.password
    INIT_OK_FILE=/nexus/init.ok
    exit_func(){
      exit 1
    }
    trap 'exit_func' EXIT HUP INT QUIT PIPE TERM
    if [ -f "$INIT_OK_FILE" ]; then
      echo "nexus init done ! skip"
      exit 0
    fi
    for (( i = 0; i < 100; i++ )); do
    echo "Wait Nexus Done ... $i"
    if [ -f "$PASSWD_PATH" ]; then
        break
    fi
      sleep 5
    done
    if [ ! -f "$PASSWD_PATH" ]; then
    echo "admin conf not found!"
      exit 1
    fi
    cat $PASSWD_PATH
    exit 0