apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-{{include "woodpecker-server.name" .}}
  namespace: {{.Release.Namespace}}
data:
  WOODPECKER_HOST: https://{{ .Values.ingress.host }}
  WOODPECKER_SERVER_ADDR: ":8080"
  WOODPECKER_OPEN: "true"
  WOODPECKER_GRPC_ADDR: ":9000"
  {{- if .Values.woodpecker.selfRepository }}
  WOODPECKER_DEFAULT_CLONE_IMAGE: "{{.Values.image.repository}}/{{.Values.image.images.cloneImage}}"
  {{- else}}
  WOODPECKER_DEFAULT_CLONE_IMAGE: "docker.io/{{.Values.image.images.cloneImage}}"
  {{- end }}
  WOODPECKER_AGENT_SECRET: "{{.Values.woodpecker.agentSecret}}"
  WOODPECKER_GITEA: "true"
  WOODPECKER_GITEA_URL: "{{.Values.woodpecker.giteaUrl}}"
  WOODPECKER_GITEA_CLIENT: "{{.Values.woodpecker.giteaOAuthID}}"
  WOODPECKER_GITEA_SECRET: "{{.Values.woodpecker.giteaOAuthSecret}}"
