apiVersion: v1
kind: Service
metadata:
  name: {{ include "woodpecker-server.name" . }}
  labels:
    {{- include "woodpecker-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 9000
      targetPort: grpc
      name: grpc
  selector:
    {{- include "woodpecker-server.selectorLabels" . | nindent 4 }}
---
  {{- if .Values.service.agent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "woodpecker-server.name" . }}-agent
  labels:
    {{- include "woodpecker-server.labels" . | nindent 4 }}
  {{- with  .Values.service.agent }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end}}
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: grpc
      name: grpc
  selector:
    {{- include "woodpecker-server.selectorLabels" . | nindent 4 }}
  {{ with .Values.service.agent.extraIP }}
  loadBalancerIP: {{ .}}
  {{ end }}
  {{ end }}
