{{ if and .Values.ldap.lam.enabled .Values.ldap.lam.ingress.enabled }}
  {{with .Values.ldap.lam.ingress}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{include "ldap.name" $ }}-lam
  namespace: {{$.Release.Namespace}}
  annotations:
    # 重写路径
    {{ if eq .ingressClass "nginx" }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{ end }}
spec:
  ingressClassName: {{.ingressClass}}
  tls:
    - hosts:
        - "{{.host}}"
      {{- with .tlsSecret }}
      secretName: "{{ . }}"
      {{- end}}
  rules:
    - host: {{.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "svc-{{include "ldap.name" $ -}}-lam"
                port:
                  name: web
{{- end}}
{{-  end }}
