{{ if .Values.ldap.lam.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: secret-{{- include "ldap.name" .}}-lam
  namespace: {{ .Release.Namespace }}
stringData:
  LAM_PASSWORD: "{{.Values.ldap.lam.password}}"
{{ end }}
