image:
  # docker.io
  repository: boot.powerk8s.cn
  pullPolicy: IfNotPresent
  images:
    gitlab: sameersbn/gitlab
    redis: library/redis:6.2
    postgres: library/postgres:12.10
persistence:
  enabled: true
  storageClass: ""
  capacity:
    gitlab: 100Gi
    redis: 10Gi
    postgres: 50Gi
external_ssh:
  enabled: true
  annotations:
    purelb.io/allow-shared-ip: default
  loadBalancerIP: ""
ingress:
  ingressClass: "nginx"
  annotations:
    host:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    pages:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    registry:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
gitlab:
  host: gitlab.powerk8s.cn
  tlsSecret: ""
  secrets:
    defaultPassword: gitlab-root-password
    dbSecrets: long-and-random-alpha-numeric-string
    sessionSecrets: long-and-random-alpha-numeric-string
    otpSecrets: long-and-random-alpha-numeric-string
    pagesSecrets: long-and-random-alpha-numeric-string
  pages:
    enabled: true
    host: public.powerk8s.cn
    tlsSecret: ""
  ldap:
    enabled: true
    label: LDAP
    host: svc-ldap.ldap-system
    port: 389
    uidColum: uid
    bindDN: cn=service-account,dc=cluster,dc=local
    bindDNPassword: service-account
    usersDN: ou=people,dc=cluster,dc=local
    usersFilter: (|(memberOf=cn=admin,ou=groups,dc=cluster,dc=local)(memberOf=cn=develop,ou=groups,dc=cluster,dc=local))
database:
  database: gitlabhq_production
  username: gitlab
  password: password
