apiVersion: v1
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "{{ .Values.network.podCIDR }}",
      "Backend": {
        "Type": "{{.Values.network.backEndType}}"
      }
    }
kind: ConfigMap
metadata:
  labels:
    app: {{.Release.Name}}
    k8s-app: {{.Release.Name}}
    tier: node
  name: {{.Release.Name}}-cfg
  namespace: {{.Release.Namespace}}
