image:
  # docker.io
  repository: boot.powerk8s.cn
  pullPolicy: IfNotPresent
  images:
    openldap: bitnami/openldap:2.6
    lam: ldapaccountmanager/lam:8.1

persistence:
  enabled: true
  storageClass:
  capacity: 10Gi

ldap:
  init:
    root: dc=cluster,dc=local
    domain: cluster.local
    peopleName: peoples
    groupName: groups
    serviceAccount:
      uid: service-account
      password: service-account
    ## 这是全局管理员，用于管理系统账户和密码
    admin:
      uid: powerk8s
      defaultPassword: powerk8s
    ## 这是默认用户，在本实例中无特殊含义
    defaultUser:
      uid: powerk8s
      defaultPassword: powerk8s
    group:
      - id: admin
        describe: 管理员角色
      - id: oci
        describe: 镜像操作员角色
      - id: develop
        describe: 项目开发者角色
      - id: library
        describe: 依赖库管理角色
      - id: package
        describe: 软件包管理角色
      - id: monitor
        describe: 集群监控管理角色
  lam:
    enabled: true
    password: admin
    ingress:
      enabled: true
      ingressClass: nginx
      host: account.powerk8s.cn
      tlsSecret:
