image:
  # docker.io
  repository: boot.powerk8s.cn
  pullPolicy: IfNotPresent
  images:
    nexus: sonatype/nexus3
    nginx: library/nginx:1.21.1
persistence:
  enabled: true
  storageClass:
  capacity: 10Gi
nexus3:
  panel:
    host: nexus.powerk8s.cn
    tlsSecret:
  dockerRegistry:
    enabled: true
    host: registry.powerk8s.cn
    tlsSecret:
  reposRegistry:
    enabled: true
    host: repos.powerk8s.cn
    tlsSecret:
    mods:
      rpm: true
      deb: true
      maven: true
  defaultPassword: "admin"
  ldap:
    enabled: true
    name: LDAP
    host: svc-ldap.ldap-system
    port: 389
    bindDN: cn=service-account,dc=cluster,dc=local
    bindDNPassword: service-account
    searchBase: dc=cluster,dc=local
    userDN: ou=peoples
    groupDN: ou=groups
    userFilter: (|(memberOf=cn=admin,ou=groups,dc=cluster,dc=local)(memberOf=cn=oci,ou=groups,dc=cluster,dc=local)(memberOf=cn=package,ou=groups,dc=cluster,dc=local)(memberOf=cn=library,ou=groups,dc=cluster,dc=local)(memberOf=cn=deploy,ou=groups,dc=cluster,dc=local))
    uidColum: uid
    mailColum: mail

ingress:
  class: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
