{{- with .Values.ldap.init}}
apiVersion: v1
kind: Secret
metadata:
  name: secret-{{include "ldap.name" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: ldap
type: Opaque
stringData:
  LDAP_ADMIN_PASSWORD: "{{.admin.defaultPassword}}" # <1>
{{- end }}
