---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "purelb.labels" . | nindent 4 }}
  name: purelb:lbnodeagent
rules:
- apiGroups:
  - purelb.io
  resources:
  - servicegroups
  - lbnodeagents
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ''
  resources:
  - endpoints
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - policy
  resourceNames:
  - lbnodeagent
  resources:
  - podsecuritypolicies
  verbs:
  - use
