---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "purelb.labels" . | nindent 4 }}
  name: purelb:lbnodeagent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: purelb:lbnodeagent
subjects:
- kind: ServiceAccount
  name: lbnodeagent
  namespace: {{ .Release.Namespace }}
