---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "purelb.labels" . | nindent 4 }}
  name: pod-lister
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - list
