apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "gitea.name" . }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gitea.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.annotations.pod }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gitea.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: gitea-init
          image: "{{include "gitea.image" .}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - su
            - "git"
            - -c
            - "cd /workspace && bash /workspace/init.sh"
          envFrom:
            - configMapRef:
                name: "conf-{{include "gitea.name" .}}"
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /workspace
              name: workspace
      containers:
        - name: {{ .Chart.Name }}
          image: "{{include "gitea.image" .}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 200
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          envFrom:
            - configMapRef:
                name: "conf-{{include "gitea.name" .}}"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: ssh
              containerPort: 22
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: data
        - name: redis
          image: "{{include "gitea.image.redis" .}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          {{- if .Values.persistence.enabled}}
          persistentVolumeClaim:
            claimName: "{{- include "gitea.name" . -}}"
          {{- else}}
          emptyDir: {}
          {{- end}}
        - name: workspace
          configMap:
            name: "resource-{{include "gitea.name" .}}"
