apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitea.name" . }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 22
      targetPort: ssh
      name: ssh
  selector:
    {{- include "gitea.selectorLabels" . | nindent 4 }}
