apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitea.name" . }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 22
      targetPort: ssh
      name: ssh
  selector:
    {{- include "gitea.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitea.name" . }}-ssh
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
  {{- with  .Values.annotations.service.ssh_lb }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end}}
spec:
  type: LoadBalancer
  ports:
    - port: 22
      targetPort: ssh
      name: ssh
  selector:
    {{- include "gitea.selectorLabels" . | nindent 4 }}
